name: physio
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.1.1
  - numpy=1.16.4
  - python=3.6.7
  - pip:
    - https://github.com/neuropsychology/NeuroKit.py/zipball/c9589348

