name: physio
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.1.1
  - numpy=1.16.4
  - python=3.6.7
  - pip
  - flake8
  - pytest
  - notebook
  - pip:
    - git+https://github.com/jdkent/NeuroKit.py.git@flex_eda_preproc

